---
version: "2.0"
services:
  tts:
    image: luke06/tts:1.0
    expose:
      - port: 8080
        as: 8080
        to:
          - global: true
    env:
      - PORT=8080
profiles:
  compute:
    tts:
      resources:
        cpu:
          units: 6
        memory:
          size: 8Gi
        storage:
          - size: 16Gi
        gpu:
          units: 1
          attributes:
            vendor:
              nvidia:
  placement:
    dcloud:
      pricing:
        tts:
          denom: uakt
          amount: 1000
deployment:
  tts:
    dcloud:
      profile: tts
      count: 1